#!/usr/bin/env python
from flask import Flask, render_template

import config

app = Flask(__name__)


@app.route('/')
def index():
    return render_template('index.html', title='Plan your journey! - Vasco')


application = app
