#!/usr/bin/env python

import os, sys

if 'OPENSHIFT_REPO_DIR' in os.environ:
     sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi',))
     virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/venv'
     os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python3.3/site-packages')
     virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
     try:
        exec(compile(open(virtualenv).read(), virtualenv, 'exec'),dict(__file__ = virtualenv))
     except IOError:
         pass



from flask import Flask, render_template

import config

app = Flask(__name__)


@app.route('/')
def index():
    return render_template('index.html', title='Plan your journey! - Vasco')


app.debug = True

application = app

if __name__ == '__main__':
    app.run()
